# THIS IS AI GENERATED BY COPILOT


import os
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch, MagicMock
from io import StringIO

# Import the CLI functions
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from hotml.cli import (
    get_file_names,
    create_files,
    final_names,
    overwrite_choices,
    DEFAULTS,
    EXTENSIONS,
)


class TestFileCreation(unittest.TestCase):
    """Test basic file creation functionality."""

    def setUp(self):
        """Set up temporary directory for each test."""
        self.test_dir = tempfile.TemporaryDirectory()
        self.original_cwd = os.getcwd()
        os.chdir(self.test_dir.name)
        final_names.clear()
        overwrite_choices.clear()

    def tearDown(self):
        """Clean up after each test."""
        os.chdir(self.original_cwd)
        self.test_dir.cleanup()

    def test_create_files_with_defaults(self):
        """Test creating files with default names."""
        with patch('builtins.input', return_value=''):
            get_file_names()
        
        create_files()
        
        self.assertTrue(Path('index.html').exists(), "index.html should be created")
        self.assertTrue(Path('style.css').exists(), "style.css should be created")
        self.assertTrue(Path('script.js').exists(), "script.js should be created")

    def test_html_file_content(self):
        """Test that HTML file has correct content."""
        with patch('builtins.input', return_value=''):
            get_file_names()
        
        create_files()
        
        with open('index.html') as f:
            content = f.read()
        
        self.assertIn('<!DOCTYPE html>', content)
        self.assertIn('<html lang="en">', content)
        self.assertIn('<title>Document</title>', content)
        self.assertIn('<link rel="stylesheet" href="style.css">', content)

    def test_css_file_content(self):
        """Test that CSS file has correct content."""
        with patch('builtins.input', return_value=''):
            get_file_names()
        
        create_files()
        
        with open('style.css') as f:
            content = f.read()
        
        self.assertIn('* {', content)
        self.assertIn('box-sizing: border-box;', content)
        self.assertIn('.container {', content)

    def test_js_file_content(self):
        """Test that JS file has correct content."""
        with patch('builtins.input', return_value=''):
            get_file_names()
        
        create_files()
        
        with open('script.js') as f:
            content = f.read()
        
        self.assertIn('console.log', content)
        self.assertIn('DOMContentLoaded', content)

    def test_create_files_with_custom_names(self):
        """Test creating files with custom names."""
        inputs = ['page.html', 'main.css', 'app.js']
        with patch('builtins.input', side_effect=inputs):
            get_file_names()
        
        create_files()
        
        self.assertTrue(Path('page.html').exists())
        self.assertTrue(Path('main.css').exists())
        self.assertTrue(Path('app.js').exists())


class TestInputValidation(unittest.TestCase):
    """Test input validation and error handling."""

    def setUp(self):
        """Set up temporary directory for each test."""
        self.test_dir = tempfile.TemporaryDirectory()
        self.original_cwd = os.getcwd()
        os.chdir(self.test_dir.name)
        final_names.clear()
        overwrite_choices.clear()

    def tearDown(self):
        """Clean up after each test."""
        os.chdir(self.original_cwd)
        self.test_dir.cleanup()

    def test_empty_filename_rejected(self):
        """Test that whitespace filenames fall back to defaults."""
        # Simulate: user enters spaces which strips to empty, uses default
        inputs = [
            '   ',  # spaces - gets stripped and uses default 'index.html'
            '',  # use default for CSS (style.css)
            '',  # use default for JS (script.js)
        ]
        
        with patch('builtins.input', side_effect=inputs):
            with patch('sys.stdout', new_callable=StringIO):
                get_file_names()
        
        self.assertIn('index.html', final_names.values())
        self.assertIn('style.css', final_names.values())

    def test_invalid_characters_rejected(self):
        """Test that filenames with invalid characters are rejected."""
        # User enters invalid chars, gets rejected, tries valid name
        inputs = [
            'index/html',  # slash invalid - rejected
            'index.html',  # valid - accepted
            'style:css',   # colon invalid - rejected
            'style.css',   # valid - accepted
            'app.js',      # valid - accepted
        ]
        
        with patch('builtins.input', side_effect=inputs):
            with patch('sys.stdout', new_callable=StringIO):
                get_file_names()
        
        self.assertIn('index.html', final_names.values())
        self.assertIn('style.css', final_names.values())
        self.assertIn('app.js', final_names.values())

    def test_duplicate_filename_detected(self):
        """Test that duplicate filenames are detected."""
        inputs = [
            'common.html',  # HTML - accepted
            'common.css',   # CSS - different name, accepted
            'common.js',    # JS - different name, accepted
        ]
        
        with patch('builtins.input', side_effect=inputs):
            with patch('sys.stdout', new_callable=StringIO):
                get_file_names()
        
        # All three should be unique
        self.assertEqual(len(set(final_names.values())), 3, "All filenames should be unique")
        self.assertEqual(len(final_names), 3, "Should have 3 files")


class TestExtensionValidation(unittest.TestCase):
    """Test file extension validation."""

    def setUp(self):
        """Set up temporary directory for each test."""
        self.test_dir = tempfile.TemporaryDirectory()
        self.original_cwd = os.getcwd()
        os.chdir(self.test_dir.name)
        final_names.clear()
        overwrite_choices.clear()

    def tearDown(self):
        """Clean up after each test."""
        os.chdir(self.original_cwd)
        self.test_dir.cleanup()

    def test_wrong_extension_warning(self):
        """Test that wrong extensions trigger warnings."""
        inputs = [
            'index.txt',  # wrong extension
            'y',  # user confirms anyway
            'style.css',
            'script.js',
        ]
        
        with patch('builtins.input', side_effect=inputs):
            with patch('sys.stdout', new_callable=StringIO) as mock_stdout:
                get_file_names()
        
        output = mock_stdout.getvalue()
        self.assertIn('Warning', output, "Should warn about wrong extension")
        self.assertIn('index.txt', final_names.values())

    def test_missing_extension_suggestion(self):
        """Test that missing extensions are suggested."""
        inputs = [
            'page',  # no extension - will trigger suggestion
            'y',  # user accepts suggestion for page.html
            '',  # use default for CSS (style.css)
            '',  # use default for JS (script.js)
        ]
        
        with patch('builtins.input', side_effect=inputs):
            get_file_names()
        
        # User accepted the suggestion, so 'page.html' should be used
        self.assertIn('page.html', final_names.values())

    def test_user_rejects_suggestion(self):
        """Test that user can use filename without extension if they reject suggestion."""
        inputs = [
            'page',  # no extension - will trigger suggestion "Did you mean 'page.html'?"
            'n',  # user rejects suggestion - accepts 'page' as-is
            '',   # use default for CSS (style.css)
            '',   # use default for JS (script.js)
        ]
        
        with patch('builtins.input', side_effect=inputs):
            with patch('sys.stdout', new_callable=StringIO):
                get_file_names()
        
        # User rejected the suggestion, so 'page' should be used (without extension)
        self.assertIn('page', final_names.values())


class TestOverwriteLogic(unittest.TestCase):
    """Test file overwrite detection and handling."""

    def setUp(self):
        """Set up temporary directory for each test."""
        self.test_dir = tempfile.TemporaryDirectory()
        self.original_cwd = os.getcwd()
        os.chdir(self.test_dir.name)
        final_names.clear()
        overwrite_choices.clear()
        
        # Create a file to test overwrite
        with open('index.html', 'w') as f:
            f.write('existing content')

    def tearDown(self):
        """Clean up after each test."""
        os.chdir(self.original_cwd)
        self.test_dir.cleanup()

    def test_existing_file_detected(self):
        """Test that existing files are detected."""
        inputs = [
            'index.html',  # file exists - will prompt for overwrite
            'y',  # confirm overwrite
            '',  # use default for CSS
            '',  # use default for JS
        ]
        
        with patch('builtins.input', side_effect=inputs):
            get_file_names()
        
        # File should be accepted with overwrite flag set
        self.assertTrue(overwrite_choices.get('HTML'), "Should mark for overwrite")

    def test_user_chooses_different_name(self):
        """Test that user can choose different name for existing file."""
        inputs = [
            'index.html',  # file exists
            'n',  # don't overwrite
            'home.html',  # try different name
            'style.css',
            'script.js',
        ]
        
        with patch('builtins.input', side_effect=inputs):
            with patch('sys.stdout', new_callable=StringIO):
                get_file_names()
        
        self.assertIn('home.html', final_names.values())
        self.assertFalse(overwrite_choices.get('HTML'), "Should not mark for overwrite")


class TestErrorHandling(unittest.TestCase):
    """Test error handling during file creation."""

    def setUp(self):
        """Set up temporary directory for each test."""
        self.test_dir = tempfile.TemporaryDirectory()
        self.original_cwd = os.getcwd()
        os.chdir(self.test_dir.name)
        final_names.clear()
        overwrite_choices.clear()

    def tearDown(self):
        """Clean up after each test."""
        os.chdir(self.original_cwd)
        self.test_dir.cleanup()

    def test_permission_error_caught(self):
        """Test that permission errors are caught gracefully."""
        # Create files normally first
        with patch('builtins.input', return_value=''):
            get_file_names()
        
        # Mock open to raise PermissionError for one file
        original_open = open
        
        def mock_open_func(filename, *args, **kwargs):
            if filename == 'index.html':
                raise PermissionError("Permission denied")
            return original_open(filename, *args, **kwargs)
        
        with patch('builtins.open', side_effect=mock_open_func):
            with patch('sys.stdout', new_callable=StringIO) as mock_stdout:
                create_files()
        
        output = mock_stdout.getvalue()
        self.assertIn('Permission denied', output, "Should report permission error")

    def test_oserror_caught(self):
        """Test that OSError is caught gracefully."""
        with patch('builtins.input', return_value=''):
            get_file_names()
        
        # Mock open to raise OSError
        original_open = open
        
        def mock_open_func(filename, *args, **kwargs):
            if filename == 'style.css':
                raise OSError("Disk full")
            return original_open(filename, *args, **kwargs)
        
        with patch('builtins.open', side_effect=mock_open_func):
            with patch('sys.stdout', new_callable=StringIO) as mock_stdout:
                create_files()
        
        output = mock_stdout.getvalue()
        self.assertIn('Error', output, "Should report OS error")

    def test_files_created_despite_error(self):
        """Test that other files are created even if one fails."""
        with patch('builtins.input', return_value=''):
            get_file_names()
        
        # Mock open to raise error only for CSS
        original_open = open
        
        def mock_open_func(filename, *args, **kwargs):
            if filename == 'style.css':
                raise OSError("Write failed")
            return original_open(filename, *args, **kwargs)
        
        with patch('builtins.open', side_effect=mock_open_func):
            with patch('sys.stdout', new_callable=StringIO):
                create_files()
        
        # HTML and JS should still be created
        self.assertTrue(Path('index.html').exists(), "HTML should be created")
        self.assertTrue(Path('script.js').exists(), "JS should be created")
        self.assertFalse(Path('style.css').exists(), "CSS should fail")


class TestDefaultsAndConstants(unittest.TestCase):
    """Test that defaults and extensions are properly configured."""

    def test_defaults_defined(self):
        """Test that default filenames are defined."""
        self.assertIn('HTML', DEFAULTS)
        self.assertIn('CSS', DEFAULTS)
        self.assertIn('JS', DEFAULTS)
        self.assertEqual(DEFAULTS['HTML'], 'index.html')
        self.assertEqual(DEFAULTS['CSS'], 'style.css')
        self.assertEqual(DEFAULTS['JS'], 'script.js')

    def test_extensions_defined(self):
        """Test that file extensions are defined."""
        self.assertIn('HTML', EXTENSIONS)
        self.assertIn('CSS', EXTENSIONS)
        self.assertIn('JS', EXTENSIONS)
        self.assertIn('.html', EXTENSIONS['HTML'])
        self.assertIn('.css', EXTENSIONS['CSS'])
        self.assertIn('.js', EXTENSIONS['JS'])


if __name__ == '__main__':
    unittest.main()
